
--RESET

DROP  USER IF EXISTS florian;
DROP  USER IF EXISTS josef;

DROP OWNED BY  READER_ROLE      CASCADE;
DROP OWNED BY  WRITER_ROLE      CASCADE;

REVOKE ALL ON SCHEMA public FROM WRITER_ROLE;
REVOKE ALL ON SCHEMA public FROM READER_ROLE;

DROP  ROLE IF EXISTS READER_ROLE;
DROP  ROLE IF EXISTS WRITER_ROLE;

--REVOKE ALL GRANTS FROM DATABASE

REVOKE CREATE  ON DATABASE postgres  FROM PUBLIC;
REVOKE CREATE  ON SCHEMA   public   FROM PUBLIC;