--CREATE ROLE

CREATE ROLE WRITER_ROLE;
CREATE ROLE READER_ROLE;

GRANT  SELECT ON ALL TABLES    IN SCHEMA public TO   WRITER_ROLE;
GRANT CREATE,USAGE ON SCHEMA public TO WRITER_ROLE;
GRANT CREATE, USAGE ON SCHEMA public TO READER_ROLE;


GRANT  SELECT ON ALL TABLES    IN SCHEMA public TO   WRITER_ROLE;
GRANT  INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO   WRITER_ROLE;
GRANT  SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO   WRITER_ROLE;

GRANT  SELECT ON ALL TABLES    IN SCHEMA public TO   READER_ROLE;
GRANT  SELECT ON ALL SEQUENCES IN SCHEMA public TO   READER_ROLE;