--CREATE USERS

CREATE USER florian WITH PASSWORD 'fg1';
CREATE USER josef WITH PASSWORD 'js1';

ALTER USER florian VALID UNTIL 'Dec 31 2018';
ALTER USER josef VALID UNTIL 'Dec 31 2018';

ALTER USER florian CREATEDB;
ALTER USER josef NOCREATEDB;

--ASSIGN ROLE TO USERS

GRANT  WRITER_ROLE TO florian;
GRANT  READER_ROLE TO josef;